from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from consec.models import TrivyReport, Vulnerability


def export_markdown(
    report: TrivyReport,
    vulns: list[Vulnerability],
    output_path: str | Path,
) -> Path:
    path = Path(output_path)
    counts = report.severity_counts()
    total = report.total_vulnerabilities

    lines = [
        f"# Security Scan Report — {report.artifact_name or 'Unknown Image'}",
        "",
        f"_Generated by consec on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"):
        lines.append(f"| {sev} | {counts.get(sev, 0)} |")
    lines.append(f"| **TOTAL** | **{total}** |")
    lines.append("")

    if not vulns:
        lines.append("✅ No vulnerabilities found.")
    else:
        lines.append("## Vulnerabilities")
        lines.append("")
        lines.append("| CVE ID | Severity | Package | Installed | Fixed | Title |")
        lines.append("|--------|----------|---------|-----------|-------|-------|")
        for v in vulns:
            fixed = v.fixed_version or "—"
            title = (v.title or "")[:60]
            lines.append(
                f"| {v.vulnerability_id} | {v.severity} | {v.pkg_name} | "
                f"{v.installed_version} | {fixed} | {title} |"
            )

    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def export_json(
    report: TrivyReport,
    vulns: list[Vulnerability],
    output_path: str | Path,
) -> Path:
    path = Path(output_path)
    data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "artifact_name": report.artifact_name,
        "total_vulnerabilities": report.total_vulnerabilities,
        "severity_counts": report.severity_counts(),
        "vulnerabilities": [
            {
                "cve_id": v.vulnerability_id,
                "severity": v.severity,
                "package": v.pkg_name,
                "installed_version": v.installed_version,
                "fixed_version": v.fixed_version,
                "has_fix": v.has_fix,
                "title": v.title,
                "target": v.target,
            }
            for v in vulns
        ],
    }
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return path
